### ISSUE TITLE
Undefined index: width height

### ISSUE THREAD

**Issue by idflorin** [backdrop-contrib/photoswipe#2]
> Notice: Undefined index: height in theme_photoswipe_image_formatter() (line 86 of C:\wamp\www\backdropcms\modules\photoswipe-1.x-2.x\photoswipe.theme.inc).

> Notice: Undefined index: width in theme_photoswipe_image_formatter() (line 86 of C:\wamp\www\backdropcms\modules\photoswipe-1.x-2.x\photoswipe.theme.inc).

**Comment by Graham-72** [comment]
@idflorin are you seeing the images you would expect to see? Getting these notices about height and width suggests that an image file is not being identified. Any more information you can supply would be helpful.

**Comment by idflorin** [comment]
Yes, but every image triggers "Notice: Undefined index" 
https://prnt.sc/mds08o
https://prnt.sc/mdrzke

**Comment by Graham-72** [comment]
@idflorin at the moment I am not getting these notices on my test installation and so I am unable to trace why Photoswipe is not receiving the image width and height information.

Is there anything more you can tell me about your usage? Are you using Photoswipe as an option within a View or from a node Display? I would like to help if I can.

**Comment by idflorin** [comment]
@Graham-72 in node display.

maybe is related to utility_image_rebuild module. 
1. I optimized all images with JPEGmicro.
2. I installed utility_image_rebuild
3. I used photoswipe with settings
"Node image style: Large (480x480)
photoswipe image style: Original image
Photoswipe Caption: Image Alt Tag"

**Comment by Graham-72** [comment]
@idflorin thank you for this information.
It is my understanding that utility_image_rebuild is a Drupal module that has not yet been ported to Backdrop. 
I fear that it has not rebuilt your image data field records correctly because of some incompatibility.
If this is the case there is not a problem in Photoswipe and we should close this issue.

Or have you ported utility_image_rebuild to Backdrop?

**Comment by idflorin** [comment]
@Graham-72  Got it. I run utility_image_rebuild for all filed and all is fine. This made me think that utility_image_rebuild works as a charm. I didn't ported but works as fine. Maybe it should be ported, it requires minimal changes or none.
Please close this issue.

**Comment by Graham-72** [comment]
No fix needed here, so closing this issue.
