### ISSUE TITLE
Photoswipe doesn't recognize multiple image fields in views as gallery 

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/photoswipe#3]
If added to a view with multiple images the Photoswipe module doesn't recognize it as a gallery. It displays only a single image without the ability to swipe/click to next or previous image. I could make it work by assigning CSS class 'photoswipe-gallery' in the view's 'Other' section.  If used for content with multivalue image field then it recognizes it as a gallery and works correctly.  I remember that same issue was in Drupal module so I think this is inherited bug, not module port related.

I have attached settings I have used for views setup (files are different only in having css 'photoswipe-gallery' assigned).

[view_photoswipe_not_working.txt](https://github.com/backdrop-contrib/photoswipe/files/2902241/view_photoswipe_not_working.txt)
[view_photoswipe_working_with_css.txt](https://github.com/backdrop-contrib/photoswipe/files/2902242/view_photoswipe_working_with_css.txt)

**Comment by Graham-72** [comment]
In the revised READMEmd of PR  https://github.com/backdrop-contrib/photoswipe/pull/5 I have described the settings needed in Views.

**Comment by korontari** [comment]
I have just noticed that if I set CSS class 'photoswipe-gallery' in the view's 'Other' section to make it work as a gallery then all links within the views stop working(like title field with link output). Not sure but this might be a Photoswipe limitation. I will try to explore it and see if there is a better way to implement gallery behavior.

**Comment by Graham-72** [comment]
Reviewing this, I think it would be better if the module were to include a modified template for views that automatically adds in the required photoswipe-gallery class and I will provide a PR for this. The template to be modified is `views-view.tpl.php`. This will save the user having to add this setting.
