### ISSUE TITLE
Library requires manual installation

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/photoswipe#4]
The module installation process requires manual installation of a library. This is exactly like it is in Drupal and is different from what is expected in Backdrop where libraries are installed automatically. Would be great to make it the Backdrop way!

**Comment by korontari** [comment]
Looks like the issue is fixed, thank you! Should we close it?

**Comment by Graham-72** [comment]
@korontari if you are happy that your issue has been satisfactorily addressed by this PR please close it.

**Comment by korontari** [comment]
Yes, thank you!
